version: '2.3'

services:

  lubm:
    container_name: fedsdm_lubm
    image: prohde/virtuoso-opensource-7:7.2.7-alpine
    ports:
      - "12000:8890"
    networks:
      - lslod
    volumes:
      - type: bind
        source: ./datasources/LUBM
        target: /database/toLoad
    mem_limit: 2g
    environment:
      DEFAULT_GRAPH: http://swat.cse.lehigh.edu/onto/univ-bench.owl#

  watdiv_product:
    container_name: fedsdm_watdiv_product
    image: prohde/virtuoso-opensource-7:7.2.7-alpine
    ports:
      - "13000:8890"
    networks:
      - lslod
    volumes:
      - type: bind
        source: ./datasources/WatDiv/watdiv_genre.ttl
        target: /database/toLoad/watdiv_genre.ttl
      - type: bind
        source: ./datasources/WatDiv/watdiv_product.ttl
        target: /database/toLoad/watdiv_product.ttl
    mem_limit: 2g
    environment:
      DEFAULT_GRAPH: http://db.uwaterloo.ca/~galuc/wsdbm/

  watdiv_role:
    container_name: fedsdm_watdiv_role
    image: prohde/virtuoso-opensource-7:7.2.7-alpine
    ports:
      - "13001:8890"
    networks:
      - lslod
    volumes:
      - type: bind
        source: ./datasources/WatDiv/watdiv_role.ttl
        target: /database/toLoad/watdiv_genre.ttl
    mem_limit: 2g
    environment:
      DEFAULT_GRAPH: http://db.uwaterloo.ca/~galuc/wsdbm/

  lslod_diseasome:
    container_name: fedsdm_lslod_diseasome
    image: prohde/virtuoso-opensource-7:7.2.7-alpine
    ports:
      - "12003:8890"
    networks:
      - lslod
    volumes:
      - type: bind
        source: ./datasources/diseasome
        target: /database/toLoad
    mem_limit: 4g
    environment:
      DEFAULT_GRAPH: http://www4.wiwiss.fu-berlin.de/diseasome/resource/diseasome

  lslod_drugbank:
    container_name: fedsdm_lslod_drugbank
    image: prohde/virtuoso-opensource-7:7.2.7-alpine
    ports:
      - "12004:8890"
    networks:
      - lslod
    volumes:
      - type: bind
        source: ./datasources/drugbank
        target: /database/toLoad
    mem_limit: 4g
    environment:
      DEFAULT_GRAPH: http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank
      
  lslod_sider:
    container_name: fedsdm_lslod_sider
    image: prohde/virtuoso-opensource-7:7.2.7-alpine
    ports:
      - "12008:8890"
    networks:
      - lslod
    volumes:
      - type: bind
        source: ./datasources/sider
        target: /database/toLoad
    mem_limit: 4g
    environment:
      DEFAULT_GRAPH: http://www4.wiwiss.fu-berlin.de/sider/resource/sider

  dashboard:
    container_name: fedsdm_dashboard
    image: fedsdm
    build:
      context: ../
      dockerfile: Dockerfile.alpine
    networks:
      - lslod
    volumes:
      - type: bind
        source: ./dashboard/sqlite
        target: /FedSDM/instance
      - type: bind
        source: ./dashboard/virtuoso/
        target: /database
    depends_on:
      - lslod_diseasome
      - lslod_drugbank
      - lslod_sider
      - lubm
      - watdiv_product
      - watdiv_role
    ports:
      - "5003:5003"
      - "18000:9000"

networks:
  lslod:
    name: fedsdm_network
    driver: bridge
