FROM python:3.12.0-alpine3.18

# Define environment variables
ENV METADATA_ENDPOINT="http://localhost:9000/sparql" \
    DEFAULT_GRAPH="http://ontario.tib.eu" \
    APP_PREFIX="/" \
    VIRT_HTTPSERVER_SERVERPORT="9000" \
    VIRT_URIQA_DEFAULTHOST="localhost:9000" \
    VIRT_PARAMETERS_NUMBEROFBUFFERS="340000" \
    VIRT_PARAMETERS_MAXDIRTYBUFFERS="250000" \
    VIRT_PARAMETERS_MAXQUERYMEM="2G" \
    VIRTUOSO_HOME="/opt/virtuoso-opensource"

# Set up prerequisites
COPY --from=prohde/virtuoso-opensource-7:7.2.11-alpine /opt/virtuoso-opensource /opt/virtuoso-opensource
RUN ln -s /opt/virtuoso-opensource/database /database &&\
    ln -s /opt/virtuoso-opensource/bin/virtuoso-entrypoint.sh /virtuoso-entrypoint.sh &&\
    addgroup -S virtuoso &&\
    adduser -D -S -G virtuoso virtuoso &&\
    chown -R virtuoso:virtuoso /opt/virtuoso-opensource &&\
    apk add --no-cache bash libldap libstdc++ curl libssl1.1

# Set the working directory to /FedSDM
WORKDIR /FedSDM

VOLUME /database
VOLUME /FedSDM/instance

COPY . /FedSDM
# Install any needed packages specified in requirements.txt
RUN python -m pip install --upgrade pip==23.3.* &&\
    python -m pip install --no-cache-dir -r /FedSDM/requirements.txt

EXPOSE 5003 9000

# Run Virtuoso and Flask
ENTRYPOINT ["/FedSDM/start-fedsdm.sh"]
