# This workflow will build the two different Docker images to see if the current state of the project can be built
name: build

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: ['Dockerfile-alpine', 'Dockerfile']
        include:
          - tag: 'fedsdm:latest'
          - tag: 'fedsdm:alpine-latest'
            dockerfile: 'Dockerfile-alpine'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python3 -m pip install -r requirements-dev.txt
          npm i
      - name: Bundle dependencies
        run: python3 bundle-assets.py
      - name: Build the Docker image from ${{ matrix.dockerfile }}
        run: docker build -f ${{ matrix.dockerfile }} . -t ${{ matrix.tag }}
